name: Validate Repository Name

on:
  create:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  check-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository name
        run: |
          REPO_NAME=${{ github.repository }}
          echo "Repository Name: $REPO_NAME"
          
          # Define naming standard here
          PATTERN='^[a-z0-9]+(-[a-z0-9]+)*$'  # Example: lower-case letters, numbers, hyphens

          if [[ ! "$REPO_NAME" =~ $PATTERN ]]; then
            echo "Repository name '$REPO_NAME' does not follow the naming standards."
            exit 1
          else
            echo "Repository name '$REPO_NAME' follows the naming standards."
          fi
